@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2MzU1ODcxOTV9.JLichCfUmIwB4gxEhjaaoS8XYf18mVDugvzPIEn_7O8

### Users create (signup)
  # POST http://localhost:3000/users
  # Content-Type: application/json

  # {
  #   "name": "nathan",
  #   "email": "nathan@gmail.com",
  #   "password": "password",
  #   "password_confirmation": "password"
  # }

  ## Sessions create (login)
  
  # POST http://localhost:3000/sessions
  # Content-Type: application/json

  # {
  #   "email": "james@gmail.com",
  #   "password": "password"
  # }

  ### Comment create 
  # POST http://localhost:3000/comments 
  # Content-Type: application/json 
  # Authorization: Bearer {{jwt}}

  # {
  #   "text": "asdfasdf blah blah",
  #   "listing_id": 2
  # }

### Comment delete
  # DELETE http://localhost:3000/comments/10
  # Content-Type: application/json 
  # Authorization: Bearer {{jwt}}

### USER SHOW
  # GET http://localhost:3000/users/
  # Content-Type: application/json 
  # Authorization: Bearer {{jwt}}